shim-version: v0.4.2@sha256:d65f769e37bbe86ffaeef42120c29c4b9de33415fcd7588a9ef7a64f609aa2a3
cvm-version: 0.6.9
cpus: 8
memory: 16384

containers:
  - name: "inference-verifier"
    image: "ghcr.io/benhagag10/inference-verification-tee:latest"
    secrets:
      - HF_TOKEN

shim:
  listen-port: 443
  upstream-port: 8080
  paths:
    - /verify
    - /health
    - /config
